version: "2"

services:
  mosquitto:
    image: ngocluanbka/virtualsensor
    volumes:
      - ./config:/home/config
  openhab:
    image: ngocluanbka/openhab
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./addons:/openhab/addons
      - ./configurations:/openhab/configurations
  